version: '3'
services:
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ENV['MYSQL_ROOT_PASSWORD']
    volumes:
      - "./mysql-data:/var/lib/mysql"

  web:
    build: .
    volumes:
      - ".:/myapp"
    ports:
      - "3002:3000"
    tty: true
    depends_on:
      - db
    
